# Generated by Django 2.2 on 2020-08-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(max_length=255)),
                ('formVideo', models.CharField(max_length=255)),
                ('formNotes', models.CharField(max_length=255)),
                ('studentVideoDoc', models.CharField(max_length=255)),
                ('instComments', models.CharField(max_length=255)),
                ('studentComments', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestedForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255)),
                ('video_doc', models.CharField(max_length=255)),
                ('test_date', models.DateField()),
                ('inst_comments', models.CharField(max_length=255)),
                ('contd_form_goals', models.CharField(max_length=255)),
                ('student_comments', models.CharField(max_length=255)),
            ],
        ),
    ]
