# Generated by Django 2.2 on 2020-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200713_1433'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forml',
            name='formLearning',
            field=models.ManyToManyField(related_name='users_fl', to='home.User'),
        ),
        migrations.AddField(
            model_name='testedform',
            name='tested_form',
            field=models.ManyToManyField(related_name='users_tf', to='home.User'),
        ),
    ]
